[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF8C00"  # Color primario de Penya (naranja)
secondaryBackgroundColor = "#F0F2F6"  # Color de fondo secundario

[client]
# Estas opciones reemplazan a las antiguas opciones de ui
showSidebarNavigation = false
toolbarMode = "minimal"


